### ISSUE TITLE
Unable to write buffer chunk to ADLS

### ISSUE THREAD

**Issue by shibug** [oleewere/fluent-plugin-azurestorage-gen2#1]
Fluentd is consuming json messages from Kafka topic and trying to write to ADLS Gen 2.  It is failing with the following error message:

> 2019-12-21 23:37:46 +0000 [info]: #0 azurestorage_gen2: Start getting access token every 3600 seconds.
2019-12-21 23:37:46 +0000 [info]: #0 azurestorage_gen2: Container 'dev' exists.
2019-12-21 23:37:46 +0000 [debug]: #0 buffer started instance=47263120461420 stage_size=0 queue_size=0
2019-12-21 23:37:46 +0000 [debug]: #0 flush_thread actually running
2019-12-21 23:37:46 +0000 [debug]: #0 enqueue_thread actually running
2019-12-21 23:37:46 +0000 [debug]: #0 fluent/log.rb:302:debug: listening http bind="0.0.0.0" port=12345
2019-12-21 23:37:46 +0000 [info]: #0 fluent/log.rb:322:info: fluentd worker is now running worker=0
2019-12-21 23:38:02 +0000 [debug]: #0 Created new chunk chunk_id="59a3f49042b23caa2e6d7e8701e1c9b4" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1576971300, tag=nil, variables=nil>
2019-12-21 23:40:00 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `chomp' for nil:NilClass"
  2019-12-21 23:40:00 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-azurestorage-gen2-0.1.1/lib/fluent/plugin/out_azurestorage_gen2.rb:110:in `block in write'
  2019-12-21 23:40:00 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.0/lib/fluent/event.rb:325:in `each'
  2019-12-21 23:40:00 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.0/lib/fluent/event.rb:325:in `block in each'
  2019-12-21 23:40:00 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.0/lib/fluent/plugin/buffer/file_chunk.rb:173:in `open'
  2019-12-21 23:40:00 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.0/lib/fluent/event.rb:324:in `each'
  2019-12-21 23:40:00 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-azurestorage-gen2-0.1.1/lib/fluent/plugin/out_azurestorage_gen2.rb:109:in `write'
  2019-12-21 23:40:00 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.0/lib/fluent/plugin/output.rb:1133:in `try_flush'
  2019-12-21 23:40:00 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.0/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
  2019-12-21 23:40:00 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.0/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
  2019-12-21 23:40:00 +0000 [warn]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.8.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-12-21 23:40:00 +0000 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_2afc4d899e90/59a3f49042b23caa2e6d7e8701e1c9b4.log

Here is my fluentd config:
```
<source>
  @type kafka_group
  @label @kafka
  brokers dsql01.ct.bnsf.com:9094,dsql02.ct.bnsf.com:9094,dsql03.ct.bnsf.com:9094
  consumer_group databricks-consumer
  topics test.databricks
  add_prefix kafka
</source>

<label @kafka>
  <filter kafka.**>
    @type record_transformer
    enable_ruby
    <record>
      event_type ${record['properties']['messageType']}
      topic ${tag_suffix[1]}
    </record>
  </filter>
  <match kafka.**>
      @type azurestorage_gen2
      @log_level debug
      azure_storage_account        my_adls
      azure_container              dev
      auto_create_container        true
      time_slice_format            %Y-%m-%d-%H
      path                         "fluentd"
      file_extension               gz
      azure_object_key_format      %{path}/%{time_slice}/events_%{index}.%{file_extension}
      utc                          true
      <buffer>
        @type file
        path /fluentd/buffer
        timekey 5m
        timekey_wait 0s
        timekey_use_utc true
        chunk_limit_size 64m
      </buffer>
  </match>
</label>
```
Any ideas what could be the problem?

**Comment by shibug** [comment]
I can see messages are buffered to the local file system but after the 5m wait, it fails to upload it to ADLS.

**Comment by oleewere** [comment]
@shibug , hi, thanks for using my plugin :) this is my first feedback here.
I guess (at first sight...but i do not know what is in the kafka input) it happens because there is no message field in the record, so it tries to call chomp on nil object.
I will fix this to make the field (that is processed and sent in the output) configurable.
i think you can workaround this if in the record transformer you would create "message" field from one of the parsed record.

btw Azure MSI is missing from your configuration, to make this work (storage access key support is in progress, i got some problem to sign the requests properly) - so if you setup MSI, it should work on azure VMs right now.

few notes:
- there are other azreustorage output plugin that can be used: https://github.com/htgc/fluent-plugin-azurestorage (no MSI but has access key support) - it uses blob api but it works on filesystem api as well. of course there is no append then (as i remember that depends on hierarchical namespace is enabled or disabled).
- my reason to build this plugin was mainly that, for larger loads, fluentd memory usage growed forever with the other azure plugin (came from the ruby http client - so i rewrote the api calls with typhoeus against filesystem api), memory leak did not happened if the load was lower (in my case i have monitored like 20+ files, those files were frequently generated logs, after every 5 minitues, the memory became larger and larger until the VM ran out of memory) - but maybe your use case is different and you can use the other plugin(s) as well for your needs

**Comment by oleewere** [comment]
one more note: https://github.com/oleewere/fluent-plugin-azurestorage-gen2#todos
so here you can see compression has not done yet (because i mainly used that with append the same files during upload), but it will be done really soon, probably i will copy the solutions from other plugins

**Comment by oleewere** [comment]
fixed in https://github.com/oleewere/fluent-plugin-azurestorage-gen2/commit/47dd91d647336e5257f8669cd8ccced4b568e9a8

**Comment by oleewere** [comment]
i will do a new release after i have finished the compression implementation

**Comment by shibug** [comment]
@oleewere 
> btw Azure MSI is missing from your configuration, to make this work (storage access key support is in progress, i got some problem to sign the requests properly) - so if you setup MSI, it should work on azure VMs right now.

I am able to connect to ADLS without providing the MSI ID. I configured the VMs to use a user managed service identify by default. So, I receive that service principle bearer token with this plugin. No issues.

**Comment by shibug** [comment]
@oleewere 
> * there are other azreustorage output plugin that can be used: https://github.com/htgc/fluent-plugin-azurestorage (no MSI but has access key support) - it uses blob api but it works on filesystem api as well. of course there is no append then (as i remember that depends on hierarchical

I didn’t try that plugin. I was under the impression that it doesn’t work on azure data lake gen 2. I will give it a try
